services:
  - type: web
    name: type2diabetes-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        sync: false
    healthCheckPath: /health
